<template>
  <div class="wrapper">
    <parallax
      class="section page-header header-filter"
      :style="headerStyle"
    ></parallax>
    <div class="main main-raised">
      <div class="section profile-content">
        <div class="container">
          <div class="md-layout">
            <div class="md-layout-item md-size-50 mx-auto">
              <div class="profile">
                <div class="avatar">
                  <img
                    src="@/assets/img/me.jpg"
                    alt="Circle Image"
                    class="img-raised rounded-circle img-fluid"
                  />
                </div>
                <div class="name">
                  <h3 class="title">Santiago Alejandro Morales Pulido</h3>
                  <h6>System engineer student</h6>
                  <md-button
                    href="javascript:void(0)"
                    class="md-just-icon md-simple md-dribbble"
                    ><i class="fab fa-dribbble"></i
                  ></md-button>
                  <md-button
                    href="javascript:void(0)"
                    class="md-just-icon md-simple md-twitter"
                    ><i class="fab fa-twitter"></i
                  ></md-button>
                  <md-button
                    href="javascript:void(0)"
                    class="md-just-icon md-simple md-pinterest"
                    ><i class="fab fa-pinterest"></i
                  ></md-button>
                </div>
              </div>
            </div>
          </div>
          <div class="description text-center">
            <H3>About me</H3>
          </div>
          <div class="description text-center">
            <p>
              I’m a systems engineering student at the National University of Colombia.
              Since I was a child I have liked maths, participating, and in many cases
              reaching the national final of the Colombian Mathematical Olympic sand
              winning some other regional group and individual competitions. This passion
              for mathematics made me choose to study in the engineering area, but which
              made me choose the systems and computing side was my taste for video games
              and the intrigue generated by knowing how these worked and how these were
              created, so I started researching and becoming interested in programming.
            </p>
          </div>
          <div class="profile-tabs">
            <tabs
              :tab-name="['Experience', 'Future projects', 'Anything else']"
              :tab-icon="['code', 'backup', 'qr_code']"
              plain
              nav-pills-icons
              color-button="success"
            >
              <!-- here you can add your content for tab-content -->
              <template slot="tab-pane-1">
                <div class="md-layout">
                  <div class="md-layout-item md-size-40 ml-auto">
                    <p>
                      Since I got in the university I have learned many programming
                      languages like C++, Java, Phyton, developing in each of these
                      languages small projects for each class. I have also worked with
                      Arduino (that since school I made quite a few projects). But what
                      struck me most was the Front-end part, developing all the logical
                      interface for a hangman game made in Android Studio, and the most
                      recent project is about a web page similar to Mercadolibre, called
                      “AgriColab”, this is a web application focused on the buy-sell of
                      farm products in order to connect the primary seller with the final
                      consumer, increasing seller profits and reducing consumer costs;
                      I am actively participating in this project developing much of the
                      web view working especially with JavaScript and it’s VueJS Framework.
                    </p>
                  </div>
                  <div class="md-layout-item md-size-15 mr-auto">
                    <img :src="tabPane1[1].image" class="rounded"/>
                    <a
                      href="https://agricolab-un.web.app/"
                      target="_blank"
                    >
                      <img :src="tabPane1[0].image" class="rounded" />
                    </a>

                  </div>
                </div>
              </template>
              <template slot="tab-pane-2">
                <div class="md-layout">
                  <div class="md-layout-item md-size-10 ml-auto">
                    <img :src="tabPane2[0].image" class="rounded" />
                    <img :src="tabPane2[1].image" class="rounded" />
                  </div>
                  <div class="md-layout-item md-size-50 mr-auto">
                    <p>
                      Finally, during my time in college, I plan to learn
                      more about front-end development knowing different
                      Frameworks and using better techniques for software
                      development, as well as understanding and learning
                      more about software engineering methodologies and
                      software architecture in order to develop better
                      projects, and if it’s possible in the future to do a
                      diplomate course or specialization in software
                      engineering in order to lead large software projects.
                    </p>
                  </div>
                </div>
              </template>
            </tabs>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { Tabs } from "@/components";
export default {
  components: {
    Tabs
  },
  bodyClass: "profile-page",
  data() {
    return {
      tabPane1: [
        { image: require("@/assets/img/green.png") },
        { image: require("@/assets/img/java.png") },
        { image: require("@/assets/img/C++.png") }
      ],
      tabPane2: [
        { image: require("@/assets/img/front.png") },
        { image: require("@/assets/img/software.png") }
      ],
      tabPane3: [
        { image: require("@/assets/img/examples/mariya-georgieva.jpg") }
      ]
    };
  },
  props: {
    header: {
      type: String,
      default: require("@/assets/img/front3.png")
    },
    img: {
      type: String,
      default: require("@/assets/img/faces/christian.jpg")
    }
  },
  computed: {
    headerStyle() {
      return {
        backgroundImage: `url(${this.header})`
      };
    }
  }
};
</script>

<style lang="scss" scoped>
.section {
  padding: 0;
}

.profile-tabs::v-deep {
  .md-card-tabs .md-list {
    justify-content: center;
  }

  [class*="tab-pane-"] {
    margin-top: 3.213rem;
    padding-bottom: 50px;

    img {
      margin-bottom: 2.142rem;
    }
  }
}
</style>
